# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a486ba7d9293834f9a6e52c3028ecb63baa851c4bb1dbcfbe6d72d47f23dcfccd40673c70d639723b0711e57b7cf844450595e8a789dac51af3bb2364ca5ad2e

test:
  secret_key_base: 76419fd374ec0f0e4d5e0656c67b6964de7a847d60ee7b7eb01c6b9f05e65b435e40dcf96445c12a096c27c3fc9a301c3135e5b7efbecdd36460137ad1605b0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
